repository_type: pipeline
lint:
  files_exist:
    - conf/modules.config
    - conf/test.config
    - conf/test_full.config
  files_unchanged:
    - LICENSE
    - assets/nf-core-rnadnavar_logo_light.png
    - docs/images/nf-core-rnadnavar_logo_dark.png
    - lib/NfcoreTemplate.groovy
    - lib/NfcoreSchema.groovy
  schema_params: False
  template_strings: False
  multiqc_config: False
