name: freebayes
description: A haplotype-based variant detector
keywords:
  - variant caller
  - SNP
  - indels
  - somatic variant calling
  - hmftools

tools:
  - sage:
      description: Bayesian haplotype-based polymorphism discovery and genotyping
      homepage: https://github.com/freebayes/freebayes
      documentation: https://github.com/hartwigmedical/hmftools/tree/master/sage
      tool_dev_url: https://github.com/hartwigmedical/hmftools/tree/master/sage
      licence: ["GPL-3.0"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - normal:
      type: file
      description: BAM/CRAM/SAM file
      pattern: "*.{bam,cram,sam}"
  - normal_index:
      type: file
      description: BAM/CRAM/SAM index file
      pattern: "*.{bai,crai}"
  - tumor:
      type: file
      description: BAM/CRAM/SAM file
      pattern: "*.{bam,cram,sam}"
  - tumor_index:
      type: file
      description: BAM/CRAM/SAM index file
      pattern: "*.{bai,crai}"
  - intervals:
      type: file
      description: BED file for intervals
      pattern: "*.bed"
  - fasta:
      type: file
      description: reference fasta file
      pattern: ".{fa,fa.gz,fasta,fasta.gz}"
  - highconfidence:
      type: file
      description: Optional.
      pattern: "*.bed"
  - actionablepanel:
      type: file
      description: Optional.
      pattern: "*.bed"
  - knownhot:
      type: file
      description: Optional.
      pattern: "*.bed"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - vcf:
      type: file
      description: Compressed VCF file
      pattern: "*.vcf.gz"
  - version:
      type: file
      description: File containing software version
      pattern: "*.{version.txt}"

authors:
  - "@RaqManzano"
