contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #rnadnavar channel"
    url: https://nfcore.slack.com/channels/rnadnavar
    about: Discussion about the nf-core/rnadnavar pipeline
